config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  scope module: "admins" do
    resources :pending_traders, only: :index, path: "traders/pending"
    resources :approved_traders, only: :update
    resources :traders
    resources :stock_transactions, only: :index, path: "transactions/stock"
    resources :balance_transactions, only: :index, path: "transactions/balance"
  end

  scope module: "traders" do
    resources :stocks, only: :index, path: "portfolio", as: "trader_stocks"

    resources :buy_stock_transactions, only: %i[index create], path: "portfolio/buy"
    get "buy/:symbol", to: "buy_stock_transactions#new", as: "new_buy_stock_transaction"

    resources :sell_stock_transactions, only: %i[index create], path: "portfolio/sell"
    get "sell/:symbol", to: "sell_stock_transactions#new", as: "new_sell_stock_transaction"

    resources :stock_transactions, only: :index, as: "trader_stock_transactions", path: "portfolio/transactions"

    resource :search_stock, only: %i[new create], path: "search"

    resource :balance, only: :show, as: "trader_balance"

    resources :balance_transactions, only: :index, as: "trader_balance_transactions", path: "balance/transactions"

    resources :deposit_balance_transactions, only: %i[index new create], path: "balance/deposit"
    resources :withdraw_balance_transactions, only: %i[index new create], path: "balance/withdraw"
  end

  root "static_pages#home"
end

app/controllers/admins/traders_controller.rb
class Admins::TradersController < ApplicationController
  before_action :authorize_admin
  before_action :set_trader, only: %i[edit update show destroy]

  def index
    @q = User.asc_traders.ransack(params[:q])
    @traders = @q.result.page(params[:page])
  end

  def show
    @trader = User.traders.find(params[:id])
  end

  def new
    @trader = User.new
  end

  def create
    @trader = User.new(trader_params)
    if @trader.save_approved_trader
      redirect_to traders_path, notice: "Trader was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trader.update(trader_update_params)
      redirect_to traders_path(@trader), notice: "Trader details was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @trader.destroy
    UserMailer.with(user: @trader.email).account_deletion_email.deliver_later
    redirect_back(fallback_location: traders_url, notice: "#{@trader.email}'s account has been successfully deleted.")
  end

  private

  def set_trader
    @trader = User.traders.find(params[:id])
  end

  def trader_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def trader_update_params
    params.require(:user).permit(:email)
  end
end

app/controllers/traders/balance_transactions_controller.rb
class Traders::BalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @balance_transactions = current_user.balance_transactions.desc_created_at.page(params[:page])
  end
end

app/controllers/traders/balances_controller.rb
class Traders::BalancesController < ApplicationController
  before_action :authorize_approved_trader

  def show
    @balance = current_user.balance
  end
end

app/controllers/traders/buy_stock_transactions_controller.rb
class Traders::BuyStockTransactionsController < ApplicationController
  before_action :authorize_trader

  def index
    @buy_transactions = current_user.stock_transactions.buy_list.page(params[:page])
  end

  def new
    @result = Iex::IexQuoteLogoRequester.new(params[:symbol]).perform
    if @result.success?
      @transaction = current_user.stock_transactions.build
      session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                          unit_price: @result.quote.latest_price}
    else
      redirect_back(fallback_location: new_search_stock_url, danger: "#{@result.message}.")
    end
  end

  def create
    @transaction = current_user.stock_transactions.build(buy_transaction_params).buy
    @stock = existing_or_new_stock_of_current_user
    @current_user_balance = current_user.subtract_amount(@transaction.amount)
    ActiveRecord::Base.transaction do
      @transaction.save!
      @stock.save!
      @current_user_balance.save!
    end
    redirect_to trader_stocks_url, success: "Successfully bought #{@transaction.quantity}
                                             share/s of #{@stock.company_name}."
  rescue ActiveRecord::RecordInvalid
    handle_record_invalid_exception
  end

  private

  def buy_transaction_params
    params.require(:buy_transaction).permit(:quantity).merge(session[:stock])
  end

  def existing_or_new_stock_of_current_user
    current_user.stocks.find_by(symbol: session[:stock]["symbol"])&.buy_share(buy_transaction_params) ||
      current_user.stocks.build(buy_transaction_params)
  end

  def handle_record_invalid_exception
    @result = Iex::IexQuoteLogoRequester.new(session[:stock]["symbol"]).perform
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
    render :new
  end
end

app/controllers/traders/deposit_balance_transactions_controller.rb
class Traders::DepositBalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @deposit_transactions = current_user.balance_transactions.deposits.page(params[:page])
  end

  def new
    @deposit_transaction = current_user.balance_transactions.build
  end

  def create
    @deposit_transaction = current_user.balance_transactions.build(deposit_transaction_params).deposit_type
    @current_user_balance = current_user.add_amount(@deposit_transaction.amount)
    ActiveRecord::Base.transaction do
      @current_user_balance.save!
      @deposit_transaction.save!
    end
    redirect_to trader_balance_url, success: "Successfully deposited $#{@deposit_transaction.amount}."
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  private

  def deposit_transaction_params
    params.require(:deposit_transaction).permit(:amount)
  end
end

app/controllers/traders/search_stocks_controller.rb
class Traders::SearchStocksController < ApplicationController
  before_action :authorize_trader

  def new; end

  def create
    if params[:symbol] == ""
      redirect_to new_search_stock_url, danger: "Please input a symbol."
    else
      redirect_to new_buy_stock_transaction_url(params[:symbol])
    end
  end
end

app/controllers/traders/sell_stock_transactions_controller.rb
class Traders::SellStockTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @sell_transactions = current_user.stock_transactions.sell_list.page(params[:page])
  end

  def new
    @stock = current_user.stocks.find_by!(symbol: params[:symbol])
    @result = Iex::IexQuoteLogoRequester.new(params[:symbol]).perform
    @transaction = current_user.stock_transactions.build
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
  end

  def create
    @transaction = current_user.stock_transactions.build(sell_transaction_params).sell
    @stock = current_user.stocks.find_by!(symbol: session[:stock]["symbol"])
      .sell_share(sell_transaction_params)
    @current_user_balance = current_user.add_amount(@transaction.amount)

    ActiveRecord::Base.transaction do
      @transaction.save!
      @stock.save!
      @current_user_balance.save!
    end
    redirect_to trader_stocks_url, success: "Successfully sold #{@transaction.quantity} share/s of #{@stock.company_name}.
                                             You received $#{@transaction.amount}."
  rescue ActiveRecord::RecordInvalid
    handle_record_invalid_exception
  end

  private

  def sell_transaction_params
    params.require(:sell_transaction).permit(:quantity).merge(session[:stock])
  end

  def handle_record_invalid_exception
    @result = Iex::IexQuoteLogoRequester.new(session[:stock]["symbol"]).perform
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
    render :new
  end
end

app/controllers/traders/stock_transactions_controller.rb
class Traders::StockTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @stock_transactions = current_user.stock_transactions.desc_created_at.page(params[:page])
  end
end

app/controllers/traders/stocks_controller.rb
class Traders::StocksController < ApplicationController
  before_action :authorize_trader

  def index
    @stocks = current_user.stocks.asc_symbol
    @stocks_value = current_user.stocks.overall_amount
    @number_of_shares = current_user.stocks.overall_shares
  end
end

app/controllers/traders/withdraw_balance_transaction_controller.rb
class Traders::WithdrawBalanceTransactionController < ApplicationController
  def new
    @withdraw_transaction = current_user.balance_transactions.build
  end

  def create
    @withdraw_transaction = current_user.balance_transactions.build(deposit_transaction_params)
    if @withdraw_transaction.save
      current_user.balance.withdraw(@withdraw_transaction.amount)
      redirect_to trader_balance_transactions_url, success: "Successfully withdrew $#{@withdraw_transaction.amount}."
    else
      render :new
    end
  end

  private

  def deposit_transaction_params
    params.require(:withdraw_transaction).permit(:balance)
  end
end

app/controllers/traders/withdraw_balance_transactions_controller.rb
class Traders::WithdrawBalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @withdraw_transactions = current_user.balance_transactions.withdrawals.page(params[:page])
  end

  def new
    @withdraw_transaction = current_user.balance_transactions.build
  end

  def create
    @withdraw_transaction = current_user.balance_transactions.build(withdraw_transaction_params).withdraw_type
    @current_user_balance = current_user.subtract_amount(@withdraw_transaction.amount)
    ActiveRecord::Base.transaction do
      @current_user_balance.save!
      @withdraw_transaction.save!
    end
    redirect_to trader_balance_url, success: "Successfully withdrew $#{@withdraw_transaction.amount}.
                                                           Remaining balance is: $#{current_user.balance}"
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  private

  def withdraw_transaction_params
    params.require(:withdraw_transaction).permit(:amount)
  end
end

app/helpers/admins/traders_helper.rb
module Admins::TradersHelper
end

app/helpers/traders/balance_transactions_helper.rb
module Traders::BalanceTransactionsHelper
end

app/helpers/traders/balances_helper.rb
module Traders::BalancesHelper
end

app/helpers/traders/buy_stock_transactions_helper.rb
module Traders::BuyStockTransactionsHelper
  def max_share(unit_price, balance)
    (balance / unit_price).truncate(1)
  end
end

app/helpers/traders/deposit_balance_transactions_helper.rb
module Traders::DepositBalanceTransactionsHelper
end

app/helpers/traders/search_stocks_helper.rb
module Traders::SearchStocksHelper
end

app/helpers/traders/sell_stock_transactions_helper.rb
module Traders::SellStockTransactionsHelper
  def check_profit
    profit = @stock.unit_price - @result.quote.latest_price
    if profit < 1
      "lose $#{profit.round(2).abs}"
    else
      "gain $#{profit.round(2)}"
    end
  end

  def change_color_if_gain_or_lose
    profit = @stock.unit_price - @result.quote.latest_price
    if profit < 1
      "text-red-500"
    else
      "text-green-500"
    end
  end
end

app/helpers/traders/stock_transactions_helper.rb
module Traders::StockTransactionsHelper
end

app/helpers/traders/stocks_helper.rb
module Traders::StocksHelper
end

app/views/traders/buy_stock_transactions/index.html.erb
<% provide(:title, 'Buy Transactions')%>
<div class='flex flex-col items-center'>
  <div class='bg-slate-100 border border-slate-300 rounded-lg py-4 px-8 w-[calc(100%-64px)]'>
    <div class='flex flex-wrap justify-between m-auto items-center gap-2'>
      <h1 class='font-bold text-3xl'> BUY Transactions </h1>
      <div class='flex flex-wrap gap-2 text-center'>
        <%= link_to "Stock Transactions", trader_stock_transactions_path, class: 'text-slate-100 font-medium bg-purple-500 rounded-md p-2 hover:bg-purple-600 text-lg' %>
        <%= link_to 'SELL Transactions', sell_stock_transactions_path, class: 'text-slate-100 font-medium bg-red-400 rounded-md p-2 hover:bg-red-500 text-lg'%>
      </div>
    </div>
    <% if @buy_transactions.count.zero? %>
      <h2 class='text-center font-bold text-3xl bg-green-400 rounded w-fit m-auto p-4 rounded-md mt-4'>No BUY Transactions to show.</h2>
    <% else %>
      <div class='overflow-auto mt-2 mx-auto'>
        <table class='bg-green-200 w-full'>
          <thead>
            <tr class='bg-green-500 text-lg text-white'>
              <th class='p-2'>Time</th>
              <th class='p-2'>Stock Transaction ID</th>
              <th class='p-2'>Symbol</th>
              <th class='p-2'>Company Name</th>
              <th class='p-2'>Quantity</th>
              <th class='p-2'>Unit Price</th>
              <th class='p-2'>Amount</th>
              <th class='p-2'>Type</th>
            </tr>
          </thead>
          <tbody>
            <%= render @buy_transactions %>
          </tbody>
        </table>
      </div>
      <%= paginate @buy_transactions, color: 'green' %>
    <% end %>
  </div>
</div>

app/views/traders/buy_stock_transactions/new.html.erb
<% provide(:title, 'Buy Shares')%>
<%= render 'shared/error_message', object: @transaction %>
<% if @stock && @current_user_balance %>
  <%= render 'shared/error_message', object: @stock %>
  <%= render 'shared/error_message', object: @current_user_balance %>
<% end %>
<div class= 'bg-slate-100 max-w-lg m-auto p-6 rounded-md mt-4 text-center'>
  <div class='flex items-center justify-center gap-2'>
    <%#= image_tag(@result.logo.url, size: '48')%>
    <h1 class='text-center text-4xl font-bold'> <%= @result.quote.symbol %> </h1>
  </div>
  <div class='mt-2 bg-slate-200 grid grid-cols-2 gap-x-1 w-auto m-auto p-4 rounded-md'>
    <p class='text-xl text-right font-bold'>Company Name: </p>
    <p class='text-left text-xl'><%= @result.quote.company_name %></p>
    <p class='text-xl text-right font-bold'>Price: </p>
    <p class='text-left text-xl'><%= number_to_currency(@result.quote.latest_price) %></p>
  </div>
  <% if current_user.approved? %>
    <div class='bg-slate-200 mt-4 p-2 rounded-md'>
      <p class='text-lg font-bold'>You currently have: <%=number_to_currency(current_user.changes[:balance]&.first || current_user.balance)%></p>
      <p class='text-lg font-bold'>You can purchase a maximum of <%=max_share(@result.quote.latest_price, current_user.changes[:balance]&.first || current_user.balance)%> shares.</p>
      <%= form_with scope: :buy_transaction, url: buy_stock_transactions_path, class: 'mt-2' do |f| %>
        <%= f.label :quantity, "Purchase share/s of #{@result.quote.symbol}:", class: 'text-xl'%>
        <%= f.number_field :quantity, step: 'any', class: 'rounded-lg border-slate-300 focus:border-green-600 focus:ring-green-600 mt-2 w-full text-center text-xl', placeholder: 'Number of shares to buy (e.g. 1, 2, 0.5, 1.5)' %>
        <%= f.submit "Purchase Stock", class: 'text-white bg-green-500 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-green-600 mt-4 w-full' %>
      <% end %>
    <% else %>
      <p class='bg-red-400 text-center rounded-md p-4 text-xl font-bold my-4'> Please wait for admin approval to purchase a stock. </p>
    <% end %>
    <hr class="border-black my-2">
    <%=link_to 'Search another stock', new_search_stock_path, class: 'text-blue-600 hover:underline font-medium text-lg'%>
  </div>
</div>