config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  scope module: "admins" do
    resources :pending_traders, only: :index, path: "traders/pending"
    resources :approved_traders, only: :update
    resources :traders
    resources :stock_transactions, only: :index, path: "transactions/stock"
    resources :balance_transactions, only: :index, path: "transactions/balance"
  end

  scope module: "traders" do
    resources :stocks, only: :index, path: "portfolio", as: "trader_stocks"

    resources :buy_stock_transactions, only: %i[index create], path: "portfolio/buy"
    get "buy/:symbol", to: "buy_stock_transactions#new", as: "new_buy_stock_transaction"

    resources :sell_stock_transactions, only: %i[index create], path: "portfolio/sell"
    get "sell/:symbol", to: "sell_stock_transactions#new", as: "new_sell_stock_transaction"

    resources :stock_transactions, only: :index, as: "trader_stock_transactions", path: "portfolio/transactions"

    resource :search_stock, only: %i[new create], path: "search"

    resource :balance, only: :show, as: "trader_balance"

    resources :balance_transactions, only: :index, as: "trader_balance_transactions", path: "balance/transactions"

    resources :deposit_balance_transactions, only: %i[index new create], path: "balance/deposit"
    resources :withdraw_balance_transactions, only: %i[index new create], path: "balance/withdraw"
  end

  root "static_pages#home"
end

app/controllers/admins/traders_controller.rb
class Admins::TradersController < ApplicationController
  before_action :authorize_admin
  before_action :set_trader, only: %i[edit update show destroy]

  def index
    @q = User.asc_traders.ransack(params[:q])
    @traders = @q.result.page(params[:page])
  end

  def show
    @trader = User.traders.find(params[:id])
  end

  def new
    @trader = User.new
  end

  def create
    @trader = User.new(trader_params)
    if @trader.save_approved_trader
      redirect_to traders_path, notice: "Trader was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trader.update(trader_update_params)
      redirect_to traders_path(@trader), notice: "Trader details was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @trader.destroy
    UserMailer.with(user: @trader.email).account_deletion_email.deliver_later
    redirect_back(fallback_location: traders_url, notice: "#{@trader.email}'s account has been successfully deleted.")
  end

  private

  def set_trader
    @trader = User.traders.find(params[:id])
  end

  def trader_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def trader_update_params
    params.require(:user).permit(:email)
  end
end

app/controllers/traders/balance_transactions_controller.rb
class Traders::BalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @balance_transactions = current_user.balance_transactions.desc_created_at.page(params[:page])
  end
end

app/controllers/traders/balances_controller.rb
class Traders::BalancesController < ApplicationController
  before_action :authorize_approved_trader

  def show
    @balance = current_user.balance
  end
end

app/controllers/traders/buy_stock_transactions_controller.rb
class Traders::BuyStockTransactionsController < ApplicationController
  before_action :authorize_trader

  def index
    @buy_transactions = current_user.stock_transactions.buy_list.page(params[:page])
  end

  def new
    @result = Iex::IexQuoteLogoRequester.new(params[:symbol]).perform
    if @result.success?
      @transaction = current_user.stock_transactions.build
      session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                          unit_price: @result.quote.latest_price}
    else
      redirect_back(fallback_location: new_search_stock_url, danger: "#{@result.message}.")
    end
  end

  def create
    @transaction = current_user.stock_transactions.build(buy_transaction_params).buy
    @stock = existing_or_new_stock_of_current_user
    @current_user_balance = current_user.subtract_amount(@transaction.amount)
    ActiveRecord::Base.transaction do
      @transaction.save!
      @stock.save!
      @current_user_balance.save!
    end
    redirect_to trader_stocks_url, success: "Successfully bought #{@transaction.quantity}
                                             share/s of #{@stock.company_name}."
  rescue ActiveRecord::RecordInvalid
    handle_record_invalid_exception
  end

  private

  def buy_transaction_params
    params.require(:buy_transaction).permit(:quantity).merge(session[:stock])
  end

  def existing_or_new_stock_of_current_user
    current_user.stocks.find_by(symbol: session[:stock]["symbol"])&.buy_share(buy_transaction_params) ||
      current_user.stocks.build(buy_transaction_params)
  end

  def handle_record_invalid_exception
    @result = Iex::IexQuoteLogoRequester.new(session[:stock]["symbol"]).perform
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
    render :new
  end
end

app/controllers/traders/deposit_balance_transactions_controller.rb
class Traders::DepositBalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @deposit_transactions = current_user.balance_transactions.deposits.page(params[:page])
  end

  def new
    @deposit_transaction = current_user.balance_transactions.build
  end

  def create
    @deposit_transaction = current_user.balance_transactions.build(deposit_transaction_params).deposit_type
    @current_user_balance = current_user.add_amount(@deposit_transaction.amount)
    ActiveRecord::Base.transaction do
      @current_user_balance.save!
      @deposit_transaction.save!
    end
    redirect_to trader_balance_url, success: "Successfully deposited $#{@deposit_transaction.amount}."
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  private

  def deposit_transaction_params
    params.require(:deposit_transaction).permit(:amount)
  end
end

app/controllers/traders/search_stocks_controller.rb
class Traders::SearchStocksController < ApplicationController
  before_action :authorize_trader

  def new; end

  def create
    if params[:symbol] == ""
      redirect_to new_search_stock_url, danger: "Please input a symbol."
    else
      redirect_to new_buy_stock_transaction_url(params[:symbol])
    end
  end
end

app/controllers/traders/sell_stock_transactions_controller.rb
class Traders::SellStockTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @sell_transactions = current_user.stock_transactions.sell_list.page(params[:page])
  end

  def new
    @stock = current_user.stocks.find_by!(symbol: params[:symbol])
    @result = Iex::IexQuoteLogoRequester.new(params[:symbol]).perform
    @transaction = current_user.stock_transactions.build
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
  end

  def create
    @transaction = current_user.stock_transactions.build(sell_transaction_params).sell
    @stock = current_user.stocks.find_by!(symbol: session[:stock]["symbol"])
      .sell_share(sell_transaction_params)
    @current_user_balance = current_user.add_amount(@transaction.amount)

    ActiveRecord::Base.transaction do
      @transaction.save!
      @stock.save!
      @current_user_balance.save!
    end
    redirect_to trader_stocks_url, success: "Successfully sold #{@transaction.quantity} share/s of #{@stock.company_name}.
                                             You received $#{@transaction.amount}."
  rescue ActiveRecord::RecordInvalid
    handle_record_invalid_exception
  end

  private

  def sell_transaction_params
    params.require(:sell_transaction).permit(:quantity).merge(session[:stock])
  end

  def handle_record_invalid_exception
    @result = Iex::IexQuoteLogoRequester.new(session[:stock]["symbol"]).perform
    session[:stock] = {company_name: @result.quote.company_name, symbol: @result.quote.symbol,
                        unit_price: @result.quote.latest_price}
    render :new
  end
end

app/controllers/traders/stock_transactions_controller.rb
class Traders::StockTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @stock_transactions = current_user.stock_transactions.desc_created_at.page(params[:page])
  end
end

app/controllers/traders/stocks_controller.rb
class Traders::StocksController < ApplicationController
  before_action :authorize_trader

  def index
    @stocks = current_user.stocks.asc_symbol
    @stocks_value = current_user.stocks.overall_amount
    @number_of_shares = current_user.stocks.overall_shares
  end
end

app/controllers/traders/withdraw_balance_transaction_controller.rb
class Traders::WithdrawBalanceTransactionController < ApplicationController
  def new
    @withdraw_transaction = current_user.balance_transactions.build
  end

  def create
    @withdraw_transaction = current_user.balance_transactions.build(deposit_transaction_params)
    if @withdraw_transaction.save
      current_user.balance.withdraw(@withdraw_transaction.amount)
      redirect_to trader_balance_transactions_url, success: "Successfully withdrew $#{@withdraw_transaction.amount}."
    else
      render :new
    end
  end

  private

  def deposit_transaction_params
    params.require(:withdraw_transaction).permit(:balance)
  end
end

app/controllers/traders/withdraw_balance_transactions_controller.rb
class Traders::WithdrawBalanceTransactionsController < ApplicationController
  before_action :authorize_approved_trader

  def index
    @withdraw_transactions = current_user.balance_transactions.withdrawals.page(params[:page])
  end

  def new
    @withdraw_transaction = current_user.balance_transactions.build
  end

  def create
    @withdraw_transaction = current_user.balance_transactions.build(withdraw_transaction_params).withdraw_type
    @current_user_balance = current_user.subtract_amount(@withdraw_transaction.amount)
    ActiveRecord::Base.transaction do
      @current_user_balance.save!
      @withdraw_transaction.save!
    end
    redirect_to trader_balance_url, success: "Successfully withdrew $#{@withdraw_transaction.amount}.
                                                           Remaining balance is: $#{current_user.balance}"
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  private

  def withdraw_transaction_params
    params.require(:withdraw_transaction).permit(:amount)
  end
end

app/helpers/admins/traders_helper.rb
module Admins::TradersHelper
end

app/helpers/traders/balance_transactions_helper.rb
module Traders::BalanceTransactionsHelper
end

app/helpers/traders/balances_helper.rb
module Traders::BalancesHelper
end

app/helpers/traders/buy_stock_transactions_helper.rb
module Traders::BuyStockTransactionsHelper
  def max_share(unit_price, balance)
    (balance / unit_price).truncate(1)
  end
end

app/helpers/traders/deposit_balance_transactions_helper.rb
module Traders::DepositBalanceTransactionsHelper
end

app/helpers/traders/search_stocks_helper.rb
module Traders::SearchStocksHelper
end

app/helpers/traders/sell_stock_transactions_helper.rb
module Traders::SellStockTransactionsHelper
  def check_profit
    profit = @stock.unit_price - @result.quote.latest_price
    if profit < 1
      "lose $#{profit.round(2).abs}"
    else
      "gain $#{profit.round(2)}"
    end
  end

  def change_color_if_gain_or_lose
    profit = @stock.unit_price - @result.quote.latest_price
    if profit < 1
      "text-red-500"
    else
      "text-green-500"
    end
  end
end

app/helpers/traders/stock_transactions_helper.rb
module Traders::StockTransactionsHelper
end

app/helpers/traders/stocks_helper.rb
module Traders::StocksHelper
end

app/views/admins/traders/edit.html.erb
<% provide(:title, "Edit Trader")%>
<%= render 'shared/error_message', object: @trader%>
<%= form_with model: @trader, url: trader_path do |f| %>
  <h1 class='text-3xl font-bold text-center mb-4'>Edit Trader</h1>
  <table class="m-auto">
    <tbody>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Email</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'rounded-xl border-slate-400 focus:border-blue-600 focus:ring-blue-600'%>
        </td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Account Confirmation</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= @trader.confirmed? ? local_time(@trader.confirmed_at,'%a, %b %d, %Y'): "Pending Email Confirmation" %></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Account Approval</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= @trader.approved? ? "Approved" : "Pending" %></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Actions</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
          <%= f.submit "Submit", class: "inline-block cursor-pointer px-6 py-2.5 bg-blue-500 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-blue-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-700 active:shadow-lg transition duration-150 ease-in-out" %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>
</div>

app/views/admins/traders/index.html.erb
<% provide(:title, 'Traders')%>
<div class= 'w-[calc(100%-64px)] m-auto'>
  <div class='flex-col justify-between gap-2 sm:flex sm:flex-row'>
    <h1 class='font-bold text-3xl'>Traders</h1>
    <div class='flex flex-wrap items-center gap-2'>
      <%= search_form_for @q, url: traders_path, method: :get do |f| %>
        <%= f.search_field :email_cont, placeholder: "Search email", class: 'rounded-2xl border-slate-300 border text-sm focus:border-blue-600 focus:ring-blue-600' %>
      <% end %>
      <%= link_to "Register Trader", new_trader_path, class: "inline-block px-6 py-2 border-2 border-gray-800 text-gray-800 font-medium text-xs leading-tight uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" %>
      <%= link_to "Pending Traders", pending_traders_path, class: "inline-block px-6 py-2 border-2 border-gray-800 text-gray-800 font-medium text-xs leading-tight uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" %>
    </div>
  </div>
  <div class='overflow-auto mt-2'>
    <% if @traders.count > 0 %>
      <table class="min-w-full">
        <tr class="border-b bg-blue-100 border-blue-200 text-xl">
          <th scope="col" class="px-6 py-4 text-center" ><%= sort_link(@q, :email, 'Email', default_order: :desc, class: 'hover:bg-blue-200 cursor-pointer p-2') %></th>
          <th scope="col" class="px-6 py-4 text-center">Email Confirmation</th>
          <th scope="col" class="px-6 py-4 text-center">Account Approval</th>
          <th scope="col" class="px-6 py-4 text-center">Registration Date</th>
          <th scope="col" class="px-6 py-4 text-center">Action</th>
        </tr>
        <tbody>
          <% @traders.each do |t| %>
            <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%=t.email%></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%= t.confirmed? ? "Confirmed" : "Pending" %></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%= t.approved? ? "Approved" : "Pending" %></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%= local_time(t.created_at, '%Y-%m-%d %l:%M %p') %></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center">
                <%= link_to "show", trader_path(t.id), class: "inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
                <%= link_to "edit", edit_trader_path(t.id), class: "inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" %>
                <%= link_to "delete", trader_path(t.id), method: :delete,  data: { confirm: "Are you sure you want to delete #{t.email}'s account?"},   class: "inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class='border-2 bg-blue-100 border-blue-400 text-xl text-center font-bold m-auto w-fit px-4 py-2 rounded-md'>There are currently no registered traders.</p>
    <% end %>
  </div>
  <%= paginate @traders, color: 'blue' %>
</div>

app/views/admins/traders/new.html.erb
<% provide(:title, 'Register Trader')%>
<%= render 'shared/error_message', object: @trader%>
<%= form_with model: @trader, url: traders_path, html: {class: 'bg-slate-100 max-w-lg m-auto p-6 rounded-md mt-4'} do |f| %>
  <h1 class='text-3xl font-bold text-center mb-4'>Register Trader</h1>
  <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email",class: 'rounded-md w-full focus:border-blue-600 focus:ring-blue-600'%>
  <%= f.password_field :password, autocomplete: "new-password", placeholder: "Password",class: 'mt-2 rounded-md w-full focus:border-blue-600 focus:ring-blue-600' %>
  <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Confirm Password",class: 'mt-2 rounded-md w-full focus:border-blue-600 focus:ring-blue-600'%>
  <%= f.submit "Create Trader Account", class: 'bg-blue-400 p-2 rounded-md cursor-pointer font-medium text-lg hover:bg-blue-500 mt-4 w-full'  %>
<% end %>
</div>

app/views/admins/traders/show.html.erb
<% provide(:title, "#{get_email_username(@trader.email)}")%>
<div class='overflow-auto mt-4 m-auto w-[calc(100%-64px)]'>
  <table class="m-auto">
    <tbody>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Email</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%=@trader.email%></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Account Confirmation</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= @trader.confirmed? ? "Confirmed" : "Pending" %></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Account Confirmation</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= @trader.confirmed? ? local_time(@trader.confirmed_at, '%Y-%m-%d %l:%M %p')  : "Pending Email Confirmation" %></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Account Approval</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= @trader.approved? ? "Approved" : "Pending" %></td>
      </tr>
      <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Actions</td>
        <td scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center"><%= link_to "edit", edit_trader_path(@trader.id), class: "inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" %></td>
      </tr>
    </tbody>
  </table>
</div>