config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  scope module: "admins" do
    resources :pending_traders, only: :index, path: "traders/pending"
    resources :approved_traders, only: :update
    resources :traders
    resources :stock_transactions, only: :index, path: "transactions/stock"
    resources :balance_transactions, only: :index, path: "transactions/balance"
  end

  scope module: "traders" do
    resources :stocks, only: :index, path: "portfolio", as: "trader_stocks"

    resources :buy_stock_transactions, only: %i[index create], path: "portfolio/buy"
    get "buy/:symbol", to: "buy_stock_transactions#new", as: "new_buy_stock_transaction"

    resources :sell_stock_transactions, only: %i[index create], path: "portfolio/sell"
    get "sell/:symbol", to: "sell_stock_transactions#new", as: "new_sell_stock_transaction"

    resources :stock_transactions, only: :index, as: "trader_stock_transactions", path: "portfolio/transactions"

    resource :search_stock, only: %i[new create], path: "search"

    resource :balance, only: :show, as: "trader_balance"

    resources :balance_transactions, only: :index, as: "trader_balance_transactions", path: "balance/transactions"

    resources :deposit_balance_transactions, only: %i[index new create], path: "balance/deposit"
    resources :withdraw_balance_transactions, only: %i[index new create], path: "balance/withdraw"
  end

  root "static_pages#home"
end

app/controllers/admins/pending_traders_controller.rb
class Admins::PendingTradersController < ApplicationController
  before_action :authorize_admin

  def index
    @q = User.pending_traders.ransack(params[:q])
    @pending_traders = @q.result.page(params[:page])
  end
end

app/helpers/admins/pending_traders_helper.rb
module Admins::PendingTradersHelper
end

app/views/admins/pending_traders/index.html.erb
<% provide(:title, 'Pending Traders')%>
<div class= 'w-[calc(100%-64px)] m-auto'>
  <div class='flex-col justify-between gap-2 sm:flex sm:flex-row'>
    <h1 class='font-bold text-3xl'>Pending Traders</h1>
    <%= search_form_for @q, url: pending_traders_path, method: :get do |f| %>
      <%= f.search_field :email_cont, placeholder: "Search email", class: 'rounded-2xl border-slate-300 border text-sm focus:border-blue-600 focus:ring-blue-600' %>
    <% end %>
  </div>
  <div class='overflow-auto mt-2'>
    <% if @pending_traders.count > 0 %>
      <table class="min-w-full">
        <tr class="border-b bg-blue-100 border-blue-200 text-xl">
          <th scope="col" class="px-6 py-4 text-center"><%= sort_link(@q, :email, 'Email', default_order: :desc, class: 'hover:bg-blue-200 cursor-pointer p-2') %></th>
          <th scope="col" class="px-6 py-4 text-center"><%= sort_link(@q, :confirmed, 'Email Confirmation', default_order: :desc, class: 'hover:bg-blue-200 cursor-pointer p-2')%> </th>
          <th scope="col" class="px-6 py-4 text-center">Registration Date</th>
          <th scope="col" class="px-6 py-4 text-center">Action</th>
        </tr>
        <tbody>
          <% @pending_traders.each do |t| %>
            <tr class="border-b bg-purple-100 border-purple-200 transition duration-300 ease-in-out hover:bg-blue-100">
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%=t.email%></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%= t.confirmed? ? "Confirmed" : "Pending" %></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center"><%= local_time(t.created_at, '%Y-%m-%d %l:%M %p') %></td>
              <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap text-center">
                <%= form_with model: t, url: approved_trader_path(t.id) do |f| %>
                  <%= f.submit "Approve", class:"inline-block px-6 mx-5 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out cursor-pointer"%>
                <% end %></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    <% else %>
      <p class='border-2 bg-blue-100 border-blue-400 text-xl text-center font-bold m-auto w-fit px-4 py-2 rounded-md'>There are currently no pending traders.</p>
    <% end %>
  </div>
  <%= paginate @pending_traders, color: 'blue' %>
</div>